input_config:
  bs: 4
  embed_dim: 1536
  kv_len: 256
  q_len: 256
  num_q_heads: 12
  num_kv_heads: 12
  num_layers: 1
  is_causal: true
  ff_dim: 4096

kernel_config:
  use_tma_reduce: true
  output_pad: 8
  warps_per_row: 1
  rows_per_rms_block: 16
  max_works: 0
  block_q: 64
  block_kv: 64
  num_stages: 2
  bM: 128
  bN: 128
  bK: 64